### PR TITLE
Update and new scripts

### PR DESCRIPTION
**Pull request by redfox-mx**
this is an update for #7 where you need to go build/web subfolder to packaging. Now, all is on the top-level folder. Update template for flutter HTML and delete no useful log and lock files because this is created by npm and pub.
I change the devDependencies to maintain script and to maintain easy electron and electron-packaging version

PD: English is not my mother tongue, please be patient and help me to improve my communication skills

### CODE REVIEW

**Comment by redfox-mx** [comment]
## tested:
- Ubunto 20.04
- Windows 10

**Comment by hayderux** [comment]
thanks

**Comment by hayderux** [comment]
Thanks

**Comment by redfox-mx** [comment]
without attention. There is no test and I do not think it is a good choice after reviewing it

**Pull request closed without merging**
